# default config
run_config:
  device: cuda
  dataset: compas
  metric: ACC
  max_epoch: 500
  learning_rate: 0.001
  batch_size: 512
  num_learner: 8
  train_ratio: 0.7
  validation_ratio: 0.1
  K_ratio: 0.3
  hidden_dim: 256
  random_state: 42
  early_stop_patience: 200
wandb_config:
  use_wandb: True  
  entity: a220284268
  project: TabularGNN_KGLM
  # project: TabularGNN ablation without GNN
  name : 3_fold with early stop
  # group: K_graph_Multi_noGraph 
  # group: KG_Multi normal
  group: KGML L=3 res cat predict:MLP dropout b512 BN selfloop no EGW
  # group: MLP baseline
  notes: V4.3 small loss 

# available datasets:
# adult
# compas
# compass_old
# covertype_num
# credit
# electricity_cat