# default config
run_config:
  device: cuda
  dataset: compass_old
  metric: ACC
  max_epoch: 20
  learning_rate: 0.001
  batch_size: 2000
  train_ratio: 0.7
  validation_ratio: 0.1
  K_ratio: 0.3
  hidden_dim: 128
  random_state: 42
wandb_config:
  use_wandb: False
  entity: a220284268
  project: TabularGNN
  name : test k_fold
  group: test k_fold
  notes: V0