# default config
run_config:
  device: cuda
  dataset: adult
  metric: ACC
  max_epoch: 50
  learning_rate: 0.001
  batch_size: 1000
  train_ratio: 0.7
  validation_ratio: 0.1
  K_ratio: 0.9

  hidden_dim: 128
  random_state: 42
wandb_config:
  use_wandb: True
  entity: a220284268
  project: TabularGNN
  name : k_fold
  group: b=1000
  notes: V1 