# default config
run_config:
  device: cuda
  dataset: credit
  metric: ACC
  max_epoch: 500
  learning_rate: 0.001
  batch_size: 1024
  num_learner: 64
  train_ratio: 0.7
  validation_ratio: 0.1
  K_ratio: 0.3
  hidden_dim: 256
  random_state: 42
  early_stop_patience: 200
wandb_config:
  use_wandb: True
  entity: a220284268
  project: TabularGNN_V3
  name : 3_fold with early stop
  group: KG_multi ES ALL_feat 64
  # group: MLP baseline
  notes: V2.5

# available datasets:
# adult
# compas
# compass_old
# covertype_num
# credit
# electricity_cat