# default config
run_config:
  device: cuda
  dataset: compas
  metric: ACC
  max_epoch: 500
  learning_rate: 0.001
  batch_size: 512
  num_learner: 1
  train_ratio: 0.7
  validation_ratio: 0.1
  K_ratio: 0.3
  hidden_dim: 256
  random_state: 42
  early_stop_patience: 200
  num_layers: 5
  layers_prop: [0.9, 0.7, 0.5, 0.3, 0.1]
  # layers_prop: [0.7, 0.5, 0.3]
wandb_config:
  use_wandb: True    
  entity: a220284268
  project: TabularGNN_V5_edge_weight_test
  # project: TabularGNN_V3
  # project: TabularGNN ablation without GNN
  name : 3_fold with early stop
  # group: K_graph_Multi_noGraph 
  # group:  KG_multi ES ALL_feat 1
  group: KGML L=5 with edge weight
  # group: MLP baseline
  notes: V5 small loss 7 5 3 res cat predict:MLP dropout b512 BN selfloop no EGW

# available datasets:
# adult
# compas
# compass_old
# covertype_num
# credit
# electricity_cat